insert into drink(id, name, drink_type) values (1, 'Caffè Americano', 'HOT_COFFEES');
insert into drink(id, name, drink_type) values (2, 'Starbucks® Blonde Caffè Americano', 'HOT_COFFEES');
insert into drink(id, name, drink_type) values (3, 'Blonde Roast', 'HOT_COFFEES');
insert into drink(id, name, drink_type) values (4, 'Pike Place® Roast', 'HOT_COFFEES');
insert into drink(id, name, drink_type) values (5, 'Chai Latte', 'HOT_TEAS');
insert into drink(id, name, drink_type) values (6, 'Teavana® Chai Tea', 'HOT_TEAS');
insert into drink(id, name, drink_type) values (7, 'Earl Grey Tea', 'HOT_TEAS');
insert into drink(id, name, drink_type) values (8, 'London Fog Tea Latte', 'HOT_TEAS');
insert into drink(id, name, drink_type) values (9, 'Royal English Breakfast Tea', 'HOT_TEAS');
insert into drink(id, name, drink_type) values (10, 'Rev Up Brewed Wellness Tea', 'HOT_TEAS');
insert into drink(id, name, drink_type) values (12, 'Cold Brew with Salted Honey Cold Foam', 'COLD_COFFEES');
insert into drink(id, name, drink_type) values (13, 'Starbucks11111 Reserve® Cold Brew', 'COLD_COFFEES');
insert into drink(id, name, drink_type) values (14, 'Starbucks® Cold Brew Coffee', 'COLD_COFFEES');
insert into drink(id, name, drink_type) values (15, 'Starbucks® Cold Brew Coffee with Milk', 'COLD_COFFEES');
insert into drink(id, name, drink_type) values (16, 'Nitro Cold Brew with Salted Honey Cold Foam', 'COLD_COFFEES');
insert into drink(id, name, drink_type) values (17, 'Iced Caffè Americano', 'COLD_COFFEES');
insert into drink(id, name, drink_type) values (18, 'Iced Espresso', 'COLD_COFFEES');
insert into drink(id, name, drink_type) values (19, 'Nitro Flat White', 'COLD_COFFEES');
insert into drink(id, name, drink_type) values (20, 'Iced Oatmilk Honey Latte', 'COLD_COFFEES');
insert into drink(id, name, drink_type) values (21, 'Iced Black Tea', 'ICED_TEAS');
insert into drink(id, name, drink_type) values (22, 'Iced Royal English Breakfast Tea Latte', 'ICED_TEAS');
insert into drink(id, name, drink_type) values (23, 'Iced Chai Tea Latte', 'ICED_TEAS');
insert into drink(id, name, drink_type) values (24, 'Matcha Lemonade', 'ICED_TEAS');
insert into drink(id, name, drink_type) values (25, 'Iced Passion Tango™ Tea', 'ICED_TEAS');
insert into drink(id, name, drink_type) values (26, 'Iced Guava White Tea Lemonade', 'ICED_TEAS');
insert into drink(id, name, drink_type) values (27, 'Iced White Tea Lemonade', 'ICED_TEAS');
